stateDiagram-v2

[*] --> SYS_STATE_INIT

SYS_STATE_INIT --> SYS_STATE_CAN_INIT

SYS_STATE_CAN_INIT --> SYS_STATE_LIDAR_WAIT

SYS_STATE_LIDAR_WAIT --> SYS_STATE_CAN_STARTED

SYS_STATE_CAN_STARTED --> SYS_STATE_RUNNING

SYS_STATE_RUNNING --> SYS_STATE_QUEUE_ERROR

SYS_STATE_RUNNING --> SYS_STATE_FAN_TX_ERROR

SYS_STATE_CAN_INIT --> SYS_STATE_CAN_START_FAILED