name=Simdaas Autonomy Core
version=1.0.0
author=Simdaas Autonomy Private Limited <support@simdaas.com>
maintainer=Simdaas Autonomy Private Limited <support@simdaas.com>
sentence=Core embedded library for Simdaas Autonomy systems.
paragraph=Provides drivers, communication modules, RTOS utilities, and system services for embedded autonomy platforms such as ESP32 and STM32.
category=Other
url=https://github.com/simdaas-autonomy/simdaas-autonomy-core
architectures=*
depends=ArduinoJson